import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service - Embertext",
  description: "Terms of Service for Embertext AI tools and Bitcoin utilities.",
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <Link
        href="/"
        className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Home
      </Link>

      <h1 className="text-3xl sm:text-4xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">
        Last updated: July 19, 2026
      </p>

      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
        <section>
          <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By accessing and using Embertext (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
            If you do not agree to these terms, please do not use the Service. We reserve the right to modify
            these terms at any time, and your continued use of the Service constitutes acceptance of any changes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
          <p className="text-muted-foreground leading-relaxed">
            Embertext provides free AI-powered tools including but not limited to:
          </p>
          <ul className="list-disc list-inside text-muted-foreground mt-2 space-y-1">
            <li>AI Text Humanizer — rewrites AI-generated text to sound more natural</li>
            <li>AI Content Detector — analyzes text to estimate AI vs human authorship</li>
            <li>AI Image Detector — analyzes images to detect AI-generated content</li>
            <li>Bitcoin Calculator — real-time cryptocurrency conversion tools</li>
            <li>Receipt Generator — creates professional transaction receipts</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">3. User Responsibilities</h2>
          <p className="text-muted-foreground leading-relaxed">
            You agree to use the Service only for lawful purposes and in accordance with these Terms.
            You are responsible for ensuring that your use of the Service does not violate any applicable
            laws or regulations. You agree not to:
          </p>
          <ul className="list-disc list-inside text-muted-foreground mt-2 space-y-1">
            <li>Use the Service to generate content that is misleading, fraudulent, or deceptive</li>
            <li>Attempt to circumvent any usage limits, rate limits, or security measures</li>
            <li>Use automated systems or bots to access the Service without written permission</li>
            <li>Interfere with or disrupt the Service or servers connected to the Service</li>
            <li>Redistribute, resell, or commercially exploit the Service without authorization</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">4. Intellectual Property</h2>
          <p className="text-muted-foreground leading-relaxed">
            The Service, including its design, code, features, and branding, is owned by Embertext and
            protected by copyright and other intellectual property laws. You retain full ownership of any
            text you input into the Service. The AI-processed output generated by the Service is provided
            to you for your use; however, you acknowledge that similar outputs may be generated for other
            users.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">5. Accuracy and Limitations</h2>
          <p className="text-muted-foreground leading-relaxed">
            The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind.
            While we strive for accuracy, we do not guarantee that:
          </p>
          <ul className="list-disc list-inside text-muted-foreground mt-2 space-y-1">
            <li>AI-generated output will be 100% accurate or suitable for any specific purpose</li>
            <li>AI detection results will be infallible or free from false positives/negatives</li>
            <li>Bitcoin price data will be real-time or free from delays</li>
            <li>The Service will be uninterrupted, secure, or error-free</li>
          </ul>
          <p className="text-muted-foreground leading-relaxed mt-3">
            You should not rely solely on the output of the Service for critical decisions, including but
            not limited to financial, legal, medical, or academic decisions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">6. Privacy</h2>
          <p className="text-muted-foreground leading-relaxed">
            Your privacy is important to us. The Service is designed to process data locally in your
            browser whenever possible. Text you input into the AI Humanizer is sent to third-party AI
            providers (Groq, NaraRouter) solely for the purpose of generating a response. We do not
            store, log, or share your input text. For complete details, please refer to our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">7. Third-Party Services</h2>
          <p className="text-muted-foreground leading-relaxed">
            The Service integrates with third-party AI providers (including Groq and NaraRouter) to
            deliver AI-powered features. Your use of these features is subject to the respective third
            party&apos;s terms and policies. We are not responsible for the availability, accuracy, or
            practices of third-party services.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
          <p className="text-muted-foreground leading-relaxed">
            To the maximum extent permitted by applicable law, Embertext shall not be liable for any
            indirect, incidental, special, consequential, or punitive damages, or any loss of profits
            or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill,
            or other intangible losses resulting from your use of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">9. Indemnification</h2>
          <p className="text-muted-foreground leading-relaxed">
            You agree to indemnify, defend, and hold harmless Embertext and its operators from any
            claims, liabilities, damages, or expenses arising from your use of the Service or your
            violation of these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">10. Changes to Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            We reserve the right to update or modify these Terms at any time without prior notice.
            Changes will be effective immediately upon posting. Your continued use of the Service
            after any changes constitutes acceptance of the new Terms. We encourage you to review
            these Terms periodically.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">11. Governing Law</h2>
          <p className="text-muted-foreground leading-relaxed">
            These Terms shall be governed by and construed in accordance with applicable laws,
            without regard to conflict of law principles.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">12. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            If you have any questions about these Terms of Service, please contact us through the
            channels available on our website.
          </p>
        </section>
      </div>
    </div>
  );
}
