import { NextResponse } from "next/server";
import { trackToolUsage } from "@/lib/analytics";

const GROQ_API_KEY = process.env.GROQ_API_KEY;
const NARAROUTER_API_KEY = process.env.NARAROUTER_API_KEY;

let providerIndex = 0;

interface ProviderConfig {
  name: string;
  url: string;
  apiKey: string | undefined;
  model: string;
}

function getProviders(): ProviderConfig[] {
  const providers: ProviderConfig[] = [];

  if (GROQ_API_KEY) {
    providers.push({
      name: "Groq AI (GPT-OSS 20B)",
      url: "https://api.groq.com/openai/v1/chat/completions",
      apiKey: GROQ_API_KEY,
      model: "openai/gpt-oss-20b",
    });
  }

  if (NARAROUTER_API_KEY) {
    providers.push({
      name: "NaraRouter (Auto)",
      url: "https://router.bynara.id/v1/chat/completions",
      apiKey: NARAROUTER_API_KEY,
      model: "gpt-4o-mini",
    });
  }

  return providers;
}

function getNextProvider(): ProviderConfig | null {
  const providers = getProviders();
  if (providers.length === 0) return null;

  const provider = providers[providerIndex % providers.length];
  providerIndex++;
  return provider;
}

function cleanHumanizedText(text: string): string {
  const providerPatterns = [
    /\b(Groq AI|Llama|Meta AI|NaraRouter|OpenAI|GPT-?[0-9]?)\b/gi,
    /\b(AI-?generated|AI-?written|generated by AI)\b/gi,
    /\b(humanized by|rewritten by|powered by)\b.*/gi,
  ];

  let cleaned = text;
  providerPatterns.forEach((pattern) => {
    cleaned = cleaned.replace(pattern, "");
  });

  return cleaned.replace(/\s{2,}/g, " ").replace(/^\s+|\s+$/g, "");
}

function parseJsonSafe(text: string): any {
  try {
    return JSON.parse(text);
  } catch {
    return {};
  }
}

function buildHumanizerPrompt(text: string, mode: string): string {
  const modeInstructions: Record<string, string> = {
    standard: "Make it sound like a real person wrote it — casual, natural, with occasional minor imperfections.",
    academic: "Make it sound like a real academic wrote it — authoritative but with personal voice, occasional hedging, and natural scholarly tone.",
    professional: "Make it sound like a seasoned professional wrote it — confident, direct, with practical insights and natural business voice.",
    creative: "Make it sound like a creative writer wrote it — expressive, vivid, with personality and emotional authenticity.",
    simple: "Make it sound like a regular person explaining something — simple, direct, conversational, maybe even a bit informal.",
  };

  return `You are a text humanization expert. Your goal is to rewrite AI-generated text so it becomes UNDETECTABLE by AI content detectors like ZeroGPT, GPTZero, or Turnitin.

CRITICAL RULES TO AVOID AI DETECTION:
1. NEVER use overly formal or perfect grammar — real humans make small mistakes
2. Vary sentence length dramatically — mix very short sentences with longer ones
3. Use contractions naturally (don't, can't, it's, etc.)
4. Add occasional colloquial phrases or informal transitions
5. Avoid repetitive structure — don't start every sentence with similar words
6. Use more personal, subjective language — add opinions, hedging, or slight exaggerations
7. Break up perfect paragraphs — real humans don't write perfectly structured content
8. Add some natural "imperfections" like minor redundancy or casual asides
9. Avoid AI-typical phrases like "furthermore", "moreover", "in conclusion", "it is important to note"
10. Use active voice more than passive voice
11. Add rhetorical questions occasionally if natural
12. Make the tone feel spontaneous, not overly polished

STYLE: ${modeInstructions[mode] || modeInstructions.standard}

Original text:
"""${text}"""

Rewrite the ENTIRE text above. Make it completely unrecognizable as AI-written while keeping the exact same meaning. Return ONLY the rewritten text, nothing else:`;
}

export async function POST(request: Request) {
  const providers = getProviders();

  if (providers.length === 0) {
    return NextResponse.json(
      { error: "No AI providers configured. Set GROQ_API_KEY or NARAROUTER_API_KEY in your .env file." },
      { status: 503 }
    );
  }

  try {
    const { text, mode } = await request.json();

    if (!text || text.trim().length < 10) {
      return NextResponse.json(
        { error: "Text must be at least 10 characters" },
        { status: 400 }
      );
    }

    const trimmedText = text.trim();
    const prompt = buildHumanizerPrompt(trimmedText, mode || "standard");

    let lastError: string | null = null;

    for (let attempt = 0; attempt < providers.length; attempt++) {
      const provider = getNextProvider();
      if (!provider) break;

      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 30000);

        const res = await fetch(provider.url, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${provider.apiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model: provider.model,
            messages: [
              {
                role: "system",
                content: "You are a text humanization expert specializing in making AI text undetectable. You rewrite text to bypass AI detectors by making it sound authentically human. Focus on natural variation, minor imperfections, colloquial language, and avoiding AI-typical patterns.",
              },
              { role: "user", content: prompt },
            ],
            temperature: 0.85,
            max_tokens: 4000,
          }),
          signal: controller.signal,
        });

        clearTimeout(timeoutId);

        if (res.ok) {
          const data = await res.json();
          const humanizedText = (data.choices?.[0]?.message?.content || "").trim();

          if (!humanizedText || humanizedText.length < trimmedText.length * 0.5) {
            lastError = `Provider ${provider.name} returned empty or too short response`;
            continue;
          }

          trackToolUsage("humanize", mode || "standard", trimmedText.split(/\s+/).length).catch(() => {});

          const cleanedText = cleanHumanizedText(humanizedText);

          return NextResponse.json({
            result: cleanedText,
            improvement: 85,
            mode: mode || "standard",
            poweredBy: provider.name,
          });
        }

        const rawText = await res.text();
        const error = parseJsonSafe(rawText);
        lastError = error.error?.message || error.detail?.message || `Provider ${provider.name} returned status ${res.status}`;

        if (res.status === 429) {
          console.log(`Rate limited on ${provider.name}, trying next provider...`);
          continue;
        }

        throw new Error(lastError || "Unknown error");
      } catch (e: any) {
        if (e.message?.includes("rate limit") || e.message?.includes("429")) {
          continue;
        }
        lastError = e.message || String(e);
        console.error(`Error with provider ${provider.name}:`, e);
      }
    }

    return NextResponse.json(
      { error: "All providers failed. " + (lastError || "Unknown error") },
      { status: 429 }
    );
  } catch (error: any) {
    console.error("Humanize API error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to humanize text" },
      { status: 500 }
    );
  }
}
